# Generated by Django 4.2.1 on 2023-06-22 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('title', models.CharField(default=None, max_length=100)),
                ('aid', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=2, max_length=6, prefix='author', primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Author',
            },
        ),
        migrations.CreateModel(
            name='Boardgame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgid', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=2, max_length=6, prefix='bg', unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='user_directory_path')),
                ('description', models.TextField(blank=True, default='This is the boardgame', null=True)),
                ('rule', models.TextField(blank=True, default='This is rule for boardgame', null=True)),
                ('age_rating', models.CharField(choices=[('G', 'Phổ biến'), ('7+', 'Trên 7 tuổi'), ('12+', 'Trên 12 tuổi'), ('16+', 'Trên 16 tuổi'), ('18+', 'Trên 18 tuổi')], default='G', max_length=5)),
                ('people', models.CharField(max_length=100)),
                ('play_time', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=99999999999999)),
                ('publication_year', models.CharField(default='2000', max_length=4)),
                ('boardgame_status', models.CharField(choices=[('out_of_stock', 'Boardgame này đã hết'), ('stocking', 'Boardgame này vẫn còn')], default='out_of_stock', max_length=20)),
                ('in_stock', models.PositiveIntegerField(default=0)),
                ('rental', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boardgame.author')),
            ],
            options={
                'verbose_name_plural': 'Boardgame',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('title', models.CharField(default=None, max_length=100)),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=2, max_length=6, prefix='cat', primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('title', models.CharField(default=None, max_length=100)),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=2, max_length=6, prefix='producer', primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Producer',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('title', models.CharField(default=None, max_length=100)),
                ('vid', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=2, max_length=6, prefix='ver', primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Version',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('boardgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='boardgame.boardgame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('boardgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardgame.boardgame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoardgameNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgnid', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=2, max_length=20, prefix='bgn', unique=True)),
                ('boardgame_number_status', models.CharField(choices=[('rental', 'Rental'), ('in_stock', 'In Stock')], default='in_stock', max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('boardgame', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boardgame_numbers', to='boardgame.boardgame')),
            ],
            options={
                'verbose_name_plural': 'BoardgameNumbers',
            },
        ),
        migrations.CreateModel(
            name='BoardgameImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='boardgame-images')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('boardgame', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boardgame.boardgame')),
            ],
            options={
                'verbose_name_plural': 'Boardgame Images',
            },
        ),
        migrations.AddField(
            model_name='boardgame',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boardgame.category'),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boardgame.producer'),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boardgame.version'),
        ),
    ]
