# Generated by Django 4.2.1 on 2023-06-23 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boardgame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardgameReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=None)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('boardgame', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='boardgame.boardgame')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Boardgame Reviews',
            },
        ),
        migrations.RemoveField(
            model_name='review',
            name='boardgame',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='boardgamenumbers',
            options={'verbose_name_plural': 'Boardgame Numbers'},
        ),
        migrations.AddField(
            model_name='boardgamenumbers',
            name='description',
            field=models.TextField(blank=True, default='This is boardgame status', null=True),
        ),
        migrations.AlterField(
            model_name='boardgamenumbers',
            name='boardgame_number_status',
            field=models.CharField(choices=[('rental', 'Rental'), ('in_stock', 'In Stock')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
