# Generated by Django 4.2.1 on 2023-06-04 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boardgame', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgame',
            name='quantity_available',
        ),
        migrations.AddField(
            model_name='boardgame',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='producer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='publication_year',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='quantity_in_stock',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='quantity_rented',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='rented_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='rule',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='status',
            field=models.CharField(choices=[('rental', 'Rental'), ('in_stock', 'In Stock')], default='in_stock', max_length=10),
        ),
    ]
