# Generated by Django 4.2.1 on 2023-07-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgame', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='publication_year',
            field=models.IntegerField(default='2000', max_length=4),
        ),
    ]
