# Generated by Django 4.2.1 on 2023-07-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgame', '0003_alter_boardgamereviews_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgamenumbers',
            name='boardgame_number_status',
            field=models.CharField(choices=[('order', 'Order'), ('rental', 'Rental'), ('in_stock', 'In Stock')], max_length=20),
        ),
    ]
