# Generated by Django 4.2.1 on 2023-07-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgame', '0004_alter_boardgame_people_alter_boardgame_play_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='people',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='play_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='publication_year',
            field=models.IntegerField(default='2000'),
        ),
    ]
