# Generated by Django 4.2.1 on 2023-07-21 11:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boardgame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('rental_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_rental_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='RentBoardgame',
            fields=[
                ('rid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rental_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('deposit_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('penalty_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('rental_status', models.CharField(blank=True, choices=[('active', 'Active'), ('replied', 'Replied'), ('expired', 'Expired')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentBoardgameItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('rental_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('boardgame_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardgame.boardgamenumbers')),
                ('rent_boardgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rent.rentboardgame')),
            ],
        ),
        migrations.AddField(
            model_name='rentboardgame',
            name='boardgames',
            field=models.ManyToManyField(related_name='rent_boardgames', through='rent.RentBoardgameItem', to='boardgame.boardgamenumbers'),
        ),
    ]
