# Generated by Django 4.2.1 on 2023-06-30 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentboardgame',
            options={'ordering': ['rid']},
        ),
        migrations.RemoveField(
            model_name='rentboardgame',
            name='id',
        ),
        migrations.AddField(
            model_name='rentboardgame',
            name='rid',
            field=models.AutoField(default='01', primary_key=True, serialize=False),
        ),
    ]
