# Generated by Django 4.2.1 on 2023-07-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentboardgame',
            name='deposit_refund_status',
            field=models.CharField(choices=[('not_refunded', 'Not Refunded'), ('refunded', 'Refunded')], default='not_refunded', max_length=20),
        ),
        migrations.AddField(
            model_name='rentboardgame',
            name='payment_status',
            field=models.CharField(choices=[('not_paid', 'Not Paid'), ('paid', 'Paid')], default='not_paid', max_length=20),
        ),
    ]
