# Generated by Django 4.2.1 on 2023-07-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentboardgame',
            name='rental_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('replied', 'Replied'), ('expired', 'Expired')], max_length=20, null=True),
        ),
    ]
