# Generated by Django 4.2.1 on 2023-06-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_alter_rentboardgame_rid'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentboardgame',
            name='deposit_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
        migrations.AddField(
            model_name='rentboardgame',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
    ]
