# Generated by Django 4.2.1 on 2023-07-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_alter_rentboardgame_boardgame_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentboardgame',
            name='penalty_price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=8),
        ),
    ]
