# Generated by Django 4.2.1 on 2023-06-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_rentboardgame_deposit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentboardgame',
            name='deposit_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='rentboardgame',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
