# Generated by Django 4.2.1 on 2023-07-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_rental_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
