# Generated by Django 4.2.1 on 2023-07-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_cart_total_rental_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='rental_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
