# Generated by Django 4.2.1 on 2023-06-30 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_alter_rentboardgame_deposit_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentboardgame',
            name='deposit_price',
        ),
        migrations.RemoveField(
            model_name='rentboardgame',
            name='total_price',
        ),
    ]
